{
    'name': 'Learning projects',
    'description': 'Learning projects',
    'author': 'Afanasiev Anton',
    'category': 'Management',
    'assets': {},
    'depends': [
        'base',
        'base_automation_webhook',
        'mail',
        'contacts',
        'project',
    ],
    'data': [
        'security/lp_security.xml',
        'security/ir.model.access.csv',
        'data/project_stage_data.xml',
        'data/automated_actions/project_status_sync_automated_action.xml',
        'data/automated_actions/project_stage_id_sync_automated_action.xml',
        'data/automated_actions/project_task_action.xml',
        'data/smtp_maildev_server.xml',
        'views/res_partner_views.xml',
        'wizards/views/lp_score_master_wizard.xml',
        'wizards/views/lp_score_lecturer_wizard.xml',
        'wizards/views/lp_load_document_wizard.xml',
        'views/lp_project_views.xml',
        'views/lp_resume_views.xml',
        'views/lp_invitation_bachelor_views.xml',
        'views/lp_interest_views.xml',
        'views/res_users_views.xml',
        'views/lp_menu.xml',
    ],
    'application': True,
    'installable': True,
}
